[build]
  base = "/"
  functions = "netlify/functions"

[functions.generateCertificateTwo2]
  included_files = ["fonts/arial.ttf"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true