[build]
  base = "/"
  functions = "netlify/functions"

[functions.generateCertificateTwoTeacher4]
  included_files = ["fonts/arial.ttf"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwoTeacher4/:id"
  status = 200
  force = true
  
  